name: Update uptime status
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 9 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Get Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Get dateutil
        run: pip install python-dateutil
      - name: Update README file
        run: python update.py
      - name: Commit
        run: |-
          git add .
          git diff
          git config --global user.email "micaelf@outlook.com"
          git config --global user.name "Micael Grilo"
          git commit -m "Update uptime status" -a || echo "..."
          git push